-- Create a SPOOL file named : hw_spool.txt
-- Create a script file named hw_script.sql
-- Create a procedure named hw1 that accepts a number that represents a price. 
-- 		The procedure will calculate the 5% GST, the 9.5% QST
-- 			and dislau on the screen the folowwing : 
--				For a price of X, you will have to pay Y GST and Z QST
-- 					And your total M 
-- 						where M = X + Y + Z

-- Ex : exec hw1(100)
-- For a price of $100, you will have to play $5 GST, $9.5 QST. Your total is $114.5.